apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: a-team
spec:
  id: a-team
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    nodeSize: medium
    minNodeCount: 1
    usage:
      enabled: true
    apps:
      traefik:
        enabled: true
      argocd:
        enabled: true
        host: argocd.44.194.69.17.nip.io
        repoURL: https://github.com/vfarcic/crossplane-kubernetes-gitops
      dapr:
        enabled: true
    namespaces:
      - dev
      - production
