apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: ateam
spec:
  id: ateam
  compositionSelector:
    matchLabels:
      provider: aws
      cluster: eks
  parameters:
    nodeSize: medium
    minNodeCount: 1
    namespaces:
      - dev
      - production
    apps:
      traefik:
        enabled: true
      argocd:
        enabled: true
        host: acme.com # FIXME:
        repoURL: https://github.com/vfarcic/SOMETHING