apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: a-team-ck
spec:
  id: a-team-ck
  compositionSelector:
    matchLabels:
      provider: civo
      cluster: ck-port
  parameters:
    nodeSize: medium
    minNodeCount: 3
