apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: cluster-civo-all
  labels:
    provider: civo
    cluster: ck-all
spec:
  compositeTypeRef:
    apiVersion: devopstoolkitseries.com/v1alpha1
    kind: CompositeCluster
  writeConnectionSecretsToNamespace: crossplane-system
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels
  resources:
  - name: kubernetes
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: ProviderConfig
      spec:
        credentials:
          source: InjectedIdentity
    patches:
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
    readinessChecks:
    - type: None
  - name: civo
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: devopstoolkitseries.com/v1alpha1
            kind: CompositeCluster
            spec:
              compositionSelector:
                matchLabels:
                  provider: civo
                  cluster: ck
    patches:
    - fromFieldPath: spec.id
      toFieldPath: spec.id
    - fromFieldPath: spec.parameters.version
      toFieldPath: spec.parameters.version
    - fromFieldPath: spec.parameters.nodeSize
      toFieldPath: spec.parameters.nodeSize
    - fromFieldPath: spec.parameters.minNodeCount
      toFieldPath: spec.parameters.minNodeCount
    - fromFieldPath: spec.id
      toFieldPath: spec.providerConfigRef.name
