apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: cluster-civo-all
  labels:
    provider: civo
    cluster: ck-all
spec:
  compositeTypeRef:
    apiVersion: devopstoolkitseries.com/v1alpha1
    kind: CompositeCluster
  writeConnectionSecretsToNamespace: crossplane-system
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels
  resources:
  - name: civo
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: devopstoolkitseries.com/v1alpha1
            kind: CompositeCluster
            spec:
              compositionSelector:
                matchLabels:
                  provider: civo
                  cluster: ck
    patches:
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: '%s-cluster-all'


